airflow:
  connections:    
    # Guardian API connection  
    - conn_id: guardian_default
      conn_type: HTTP
      conn_host: content.guardianapis.com  # just the domain url
      conn_port: 443
      conn_schema: https  # tell Airflow to use HTTPS
      conn_extra: '{"timeout": 30}'
    
    # PostgreSQL connection (Neon)
    - conn_id: postgres_default
      conn_type: postgres
      conn_host: ep-aged-recipe-a1t83gta-pooler.ap-southeast-1.aws.neon.tech
      conn_port: 5432
      conn_schema: neondb
      conn_login: neondb_owner
      conn_password: npg_GxW0sRMrjBh2
      conn_extra: '{"sslmode": "require", "channel_binding": "require"}'
  
  variables:
    # API Keys and other variables
    # Guardian API key
    - variable_name: GUARDIAN_API_KEY
      variable_value: "0dbf2cb9-d09a-468e-82f3-0c0ffda75cff"
    
    # OpenAI API key
    - variable_name: GEMINI_API_KEY
      variable_value: "AIzaSyC5qg123Pv7c76m9Vib6GtmM4_jTLxl4L8"

  pools:
    # Resource pools if needed
    - pool_name: api_pool
      pool_slot: 5
      pool_description: "Pool for external API calls"